version: '3.11'

services:

  web:
    build:
      context: .
      dockerfile: compose/local/django/Dockerfile
    volumes:
      - ./src:/app
    ports:
      - "8000:8000"
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    depends_on:
      - db
    stdin_open: true
    tty: true

  nginx:
    container_name: nginx
    working_dir: /app
    image: nginx:stable-alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/dev/:/etc/nginx/conf.d:ro
    links:
      - web
    depends_on:
      - web

  db:
    image: postgres:13.0-alpine
    ports:
      - "30333:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .envs/.local/.postgres

  telegram-bot:
    build:
      context: .
      dockerfile: compose/local/bot/Dockerfile
    env_file:
      - ./.envs/.local/.bot
    container_name: cutter_bot
    restart: unless-stopped
    volumes:
      - ./src/bot:/app


volumes:
  postgres_data: {}