# Generated by Django 4.2.1 on 2023-06-15 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_url_original_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='original_url',
            new_name='url',
        ),
    ]
