# Generated by Django 4.2.1 on 2023-06-19 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_original_url_url_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='created_date',
            new_name='created',
        ),
    ]
