# Generated by Django 4.2.1 on 2023-06-06 07:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='full_url',
            new_name='original_url',
        ),
        migrations.AddField(
            model_name='url',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='url',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='url',
            name='requests_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='url',
            name='short_url',
            field=models.CharField(blank=True, db_index=True, max_length=20, unique=True),
        ),
    ]
