# Generated by Django 4.2.1 on 2023-06-13 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_url_requests_count_alter_url_short_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='short_url',
            field=models.CharField(blank=True, db_index=True, max_length=20, unique=True),
        ),
    ]
