# Generated by Django 4.2.2 on 2023-06-29 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_url_qr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='qr',
        ),
    ]
