# Generated by Django 4.2.2 on 2023-08-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_url_qr'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='redirect_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='url',
            name='url',
            field=models.TextField(max_length=2500, unique=True),
        ),
    ]
