# Generated by Django 4.2.1 on 2023-06-13 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_full_url_url_original_url_url_created_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='requests_count',
        ),
        migrations.AlterField(
            model_name='url',
            name='short_url',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
    ]
