# Generated by Django 4.2.1 on 2023-06-19 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_created_date_url_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='short_url',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
    ]
