name: CI/CD Deployment

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11  # Change this to your desired Python version

      - name: Run command on remote server
        uses: D3rHase/ssh-command-action@v0.2.2
        with:
          host: ${{secrets.SSH_HOST}}
          user: ${{secrets.SSH_USER}}
          private_key: ${{secrets.SSH_PRIVATE_KEY}}
          command: |
            cd ..;
            cd ${{ secrets.PROJECT_FOLDER }};
            git checkout main;
            git pull;
            docker compose -f prod.yml down;
            docker compose -f prod.yml down up -d;
            docker system prune --all --force;

