name: CI/CD Deployment

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11  # Change this to your desired Python version

      - name: Install dependencies
        run: pip install -r /requirements/prod.txt

      # Add your test steps here if needed

      - name: Deploy to server
        env:
          SERVER_SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}  # Add your secret name for the server SSH key
          SERVER_USER: root
          SERVER_HOST: 90.156.225.6
          PROJECT_DIR: /home/cutter
        run: |
          echo "$SERVER_SSH_KEY" > /tmp/server_key
          chmod 600 /tmp/server_key
          scp -i /tmp/server_key -r . $SERVER_USER@$SERVER_HOST:$PROJECT_DIR
          ssh -i /tmp/server_key $SERVER_USER@$SERVER_HOST 'bash -s' < deploy.sh

